name: JVM Publish Action

on:
  workflow_call:
    inputs:
      release:
        description: "Whether to perform a release publish"
        required: false
        type: boolean
        default: false
      java-version:
        description: "Optional java version"
        required: false
        type: string
        default: "21"
      java-distribution:
        description: "Optional java distribution"
        required: false
        type: string
        default: "zulu"
      build-cache:
        description: "Cache to use for the build tool"
        required: false
        type: string
        default: "gradle"
      publish-command:
        description: "Optional publish command to run (default to ./gradlew publish)"
        required: false
        type: string
        default: "./gradlew publish"
      default-branch:
        description: "Default branch to check for releases"
        required: false
        type: string
        default: "main"
      runs-on:
        description: "Optional label for the runner to run on"
        required: false
        type: string
        default: "['ubuntu-latest']"
    secrets:
      MAVEN_USERNAME:
        description: "Username for Maven repository"
        required: true
      MAVEN_PASSWORD:
        description: "Password for Maven repository"
        required: true

jobs:
  publish:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-distribution }}
          cache: ${{ inputs.build-cache }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@f29f5a9d7b09a7c6b29859002d29d24e1674c884 # v5

      - name: Make the short sha
        id: short_sha
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Publish project
        env:
          RELEASE: ${{ inputs.release }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        run: |
          if [ ! -x ./gradlew ]; then
            chmod +x ./gradlew
          fi

          if [ "$RELEASE" != "true" ]; then
            ${{ inputs.publish-command }}
          else
            ${{ inputs.publish-command }} -Drepository.name=releases
          fi
